apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore
  namespace: default
  labels:
    app: petstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petstore
  template:
    metadata:
      labels:
        app: petstore
    spec:
      containers:
      - name: petstore
        image: quay.io/sololabs/petstore:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 16Mi
          limits:
            cpu: 250m
            memory: 32Mi
        livenessProbe:
          httpGet:
            path: /api/pets
            port: http
          initialDelaySeconds: 1
          periodSeconds: 1
        readinessProbe:
          httpGet:
            path: /api/pets
            port: http
          initialDelaySeconds: 1
          periodSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: petstore
  namespace: default
  labels:
    app: petstore
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: petstore
